### ISSUE TITLE
Recipe package_repo.rb fails on amazon platform

### ISSUE THREAD

**Issue by ghost** [phlipper/chef-percona#130]
Hey,
on package_repo.rb case rhel will be used for platform amazon. this results in the var pversion being set to whatever year the amazon AMI had been released (in my case 2013) which results in a 404 during the repo update.

Is there a chance that this case gets set to fall back to the centos 6 option? right now i*m hacking around wiht a wrapper cookbook, but that just seems to fail all along...

**Comment by whysthatso** [comment]
works great, thanks
