### ISSUE TITLE
The cluster configuration is no longer correct

### ISSUE THREAD

**Issue by tkuhlman** [phlipper/chef-percona#199]
When pulling from master the latest cookbook has a broken cluster config. Likely caused by this checkin, https://github.com/phlipper/chef-percona/commit/8a5c4905b12d71470f34f75b25ec1e4aa01f80d6

Pulling from the 0.15.5 tag works fine.

**Comment by jharley** [comment]
I think I've restored the original configuration functionality in PR #239

**Comment by phlipper** [comment]
This has been resolved via #240. Thanks @jharley!
