### ISSUE TITLE
Plans to support chef-vault for secret's encryption?

### ISSUE THREAD

**Issue by wubrg** [phlipper/chef-percona#243]
title. Our org is switching over to percona xtradb cluster and is evaluating this cookbook to help us manage and deploy the cluster. We use chef-vault to handle encryption rather than the encrypted databags that this cookbook uses. We can work around this, but would like to know if there are any plans or if there is any interest in adding chef-vault support to this cookbook?

**Comment by jharley** [comment]
There is an open pull request (#242) for this functionality.

**Comment by phlipper** [comment]
@wubrg thanks for the interest. I will am planning on evaluating and testing the support in PR #242 this weekend, so there will likely be support for chef-vault soon.

**Comment by wubrg** [comment]
@phlipper Awesome! Thanks for the quick reply!

**Comment by phlipper** [comment]
A quick update: I've been out sick and haven't had the time or energy to get this wrapped up yet. It is on my radar and I will get to it soon, I have not forgotten about it or changed my mind.
