### ISSUE TITLE
uninitialized constant Chef::Node::Opscode

### ISSUE THREAD

**Issue by ikozel** [phlipper/chef-percona#250]
Seeing this error with or without  openssl cookbook. 

The line that couseing this error:  
::Chef::Node.send(:include, Opscode::OpenSSL::Password)

Any suggestion how to fix this? 

Starting Chef Client, version 12.0.3
       [2015-02-20T00:13:46+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["openssl", "flite-cookbook::mysql_server"]
       Synchronizing Cookbooks:
         - chef-sugar
         - openssl
         - flite-cookbook
         - apt
         - percona
         - yum
       Compiling Cookbooks...
       
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/percona/attributes/default.rb
       ================================================================================
       
       NameError
       ---------
       uninitialized constant Chef::Node::Opscode
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/percona/attributes/default.rb:6:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/percona/attributes/default.rb:
       
         1:  #
         2:  # Cookbook Name:: percona
         3:  # Attributes:: default
         4:  #
         5:  
         6>> ::Chef::Node.send(:include, Opscode::OpenSSL::Password)
         7:  
         8:  version = default["percona"]["version"] = "5.6"
         9:  
        10:  # Always restart percona on configuration changes
        11:  default["percona"]["auto_restart"] = true
        12:  
        13:  case node["platform_family"]
        14:  when "debian"
        15:    default["percona"]["server"]["socket"]                        = "/var/run/mysqld/mysqld.sock"
       
       
       Running handlers:
       [2015-02-20T00:13:48+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-02-20T00:13:48+00:00] ERROR: Exception handlers complete
       [2015-02-20T00:13:48+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 5.451611262 seconds
       [2015-02-20T00:13:48+00:00] ERROR: uninitialized constant Chef::Node::Opscode
       [2015-02-20T00:13:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by jharley** [comment]
The 3.0.0 OpenSSL cookbook is not the most safe.  @arnesund opened #248  today to fix this, but you can also add a metadata.rb ``depends 'openssl', '< 3.0.0'`` to a wrapper cookbook and you'll be good to go if you don't want to just pull in his branch.

**Comment by ikozel** [comment]
specified 2.0.2 and got the same error.. 

     On Thursday, February 19, 2015 4:22 PM, Jason Harley <notifications@github.com> wrote:
   

 The 3.0.0 OpenSSL cookbook is not the most safe. @arnesund opened #248 today to fix this, but you can also add a metadata.rb depends 'openssl', '< 3.0.0' to a wrapper cookbook and you'll be good to go if you don't want to just pull in his branch.—
