### ISSUE TITLE
Regression: cluster template redefines 'binlog_format' using the wrong value

### ISSUE THREAD

**Issue by jharley** [phlipper/chef-percona#283]
PXC only currently supports 'ROW' as a binlog_format mode, but I introduced a regression in b3de2db206c4dbc27ebe35efb6da1607ea9c1187 which re-defined 'binlog_format' later on using the value from ```['percona']['server']['binlog_format']```

**Comment by jharley** [comment]
PXC users: as a temporary workaround just set the ```['percona']['server']['binlog_format']``` attribute to 'ROW'.

My apologies for the mixup.

**Comment by phlipper** [comment]
Fixed via #299.
