### ISSUE TITLE
auto restart by default might be an unexpected surprise

### ISSUE THREAD

**Issue by wjimenez5271** [phlipper/chef-percona#314]
Just wanted to raise the perspective that restarting mysql after every change might be an unexpected default that could surprise people in a not so pleasant way. If there are reasons for this being the way it is, I understand, but just wanted to bring it up in case it wasn't considered yet.

**Comment by phlipper** [comment]
@wjimenez5271 that's what the [`auto_restart`](https://github.com/phlipper/chef-percona/blob/master/attributes/default.rb#L18) attribute is for.

**Comment by wjimenez5271** [comment]
@phlipper yes and thats set to `true` by default. I'm suggesting it might be more user friendly to set that to `false` by default instead, so the user has to explicitly enable that behavior.
