### ISSUE TITLE
Error executing action `run` on resource 'execute[install-key 0x1C4CBDCDCD2EFD2A]'

### ISSUE THREAD

**Issue by daugustus** [phlipper/chef-percona#324]
9 out of 10 runs fail with this error.  Using version 0.16.0. Here is the Chef output:

Recipe: percona::package_repo
  * apt_preference[00percona] action add
    * directory[/etc/apt/preferences.d] action create (up to date)
    * file[/etc/apt/preferences.d/00percona] action delete (up to date)
    * file[/etc/apt/preferences.d/00percona.pref] action create (up to date)
     (up to date)
  * apt_repository[percona] action add
    * execute[install-key 0x1C4CBDCDCD2EFD2A] action run

      
      Error executing action `run` on resource 'execute[install-key 0x1C4CBDCDCD2EFD2A]'

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '2'
      ---- Begin output of apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv 0x1C4CBDCDCD2EFD2A ----
      STDOUT: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.pUpunNo8oe --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keys.gnupg.net:80 --recv 0x1C4CBDCDCD2EFD2A
      gpgkeys: key 1C4CBDCDCD2EFD2A not found on keyserver
      STDERR: gpg: requesting key CD2EFD2A from hkp server keys.gnupg.net
      gpg: no valid OpenPGP data found.
      gpg: Total number processed: 0
      ---- End output of apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv 0x1C4CBDCDCD2EFD2A ----
      Ran apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv 0x1C4CBDCDCD2EFD2A returned 2

**Comment by jharley** [comment]
```keys.gnupg.net``` is quite a mess.  I've been using ```hkp://keyserver.ubuntu.com:80``` as my keyserver for a number of months without issue.

**Comment by daugustus** [comment]
Just added that to my overrides and it worked the first time. Thanks for the answer...and so quick! I am going to leave this open for now. I would assume that if this works as designed, then the keyserver value in the cookbook should be changed permanently.

**Comment by daugustus** [comment]
After several weeks of running in PRD with this change, the issue is resolved.
