### ISSUE TITLE
mysql-install-priviledges - percona::access_grants line 28

### ISSUE THREAD

**Issue by awworrell** [phlipper/chef-percona#371]
On line 28 in access_grants, I receive an error. Inside the error logs, it seems there was an issue saving the client.pem file to the server under /etc/chef/client.pem. Would you all happen to know how to fix this? I have attempted to run this as sudo but that doesn't seem to fix the issue

**Comment by joelhandwell** [comment]
Hi @awworrell you can talk this in https://github.com/phlipper/chef-percona/issues/362

**Comment by awworrell** [comment]
Thanks.
